use_frameworks!
platform :ios, '10.0'

target 'Swamp_Test-iOS' do
  inherit! :search_paths
  pod 'Swamp', :path => '../'

  pod 'Quick', '~> 0.10.0'
  pod 'Nimble', '~> 5.0.0'
end

target 'Swamp_Test-OSX' do
    inherit! :search_paths
    pod 'Swamp', :path => '../'

    pod 'Quick', '~> 0.10.0'
    pod 'Nimble', '~> 5.0.0'
end
